---
resource_types:
- name: git
  type: registry-image
  source:
    repository: us-west2-docker.pkg.dev/mapbu-cryogenics/dockerhub-proxy-cache/concourse/git-resource
    tag: ubuntu
    username: _json_key
    password: ((gcp-tas-runtime-service-account/config-json))

resources:
- name: repo
  type: git
  icon: source-branch
  source:
    branch: develop
    private_key: ((github-tas-runtime-bot/private-key))
    uri: git@github.com:cloudfoundry/mapfs-release.git
    ignore_paths:
    - .github/
    - .gitignore
    - .final_build
    - CODEOWNERS
    - LICENSE
    - NOTICE
    - README*
    - docs/
    - releases/

- name: release-branch
  type: git
  icon: source-branch
  source:
    branch: release
    private_key: ((github-tas-runtime-bot/private-key))
    uri: git@github.com:cloudfoundry/mapfs-release.git

- name: develop-branch-mergeback
  type: git
  icon: source-branch
  source:
    uri: git@github.com:cloudfoundry/mapfs-release.git
    branch: develop
    private_key: ((github-tas-runtime-bot/private-key))

- name: ci
  type: git
  icon: source-branch
  source:
    branch: main
    uri: https://github.com/cloudfoundry/wg-app-platform-runtime-ci

- name: image
  type: docker-image
  icon: docker
  source:
    repository: us-central1-docker.pkg.dev/cf-diego-pivotal/tas-runtime-dockerhub-mirror/cloudfoundry/tas-runtime-build
    tag: 'latest'
    username: _json_key
    password: ((gcp-tas-runtime-service-account/config-json))

jobs:
- name: test-mergeback
  serial: true
  plan:
  - in_parallel:
      steps:
      - get: ci
      - get: repo
      - get: release-branch
      - get: develop-branch-mergeback
      - get: image
  - do:
    - task: make-release
      image: image
      file: repo/task.yml
      params:
        FILE: release
        CONTENT: blarg-releasing-new-version
      input_mapping:
        repo: release-branch
      output_mapping:
        updated-repo: updated-release-branch
    - put: release-branch
      params:
        repository: updated-release-branch
    - task: merge-release-onto-develop
      image: image
      file: ci/shared/tasks/git-merge-branches/linux.yml
      input_mapping:
        source-branch: release-branch
        onto-branch: develop-branch-mergeback
      params:
        SOURCE_BRANCH_NAME: release
        ONTO_BRANCH_NAME: develop
    - task: modify-dev-branch
      image: image
      file: repo/task.yml
      params:
        FILE: release
        CONTENT: blarg-releasing-new-version
      input_mapping:
        repo: repo
      output_mapping:
        updated-repo: updated-repo
    - put: repo
      params:
        repository: updated-repo
    - put: repo
    - put: develop-branch-mergeback
      params:
        repository: merged-branch

